### ISSUE TITLE
Personalize auto deploy failed. 

### ISSUE THREAD

**Issue by patrick-239** [aws-samples/retail-demo-store#219]
Create a new deployment with auto personalize provisioning and in logs I could see a following continuous error:
[ERROR] ResourceAlreadyExistsException: An error occurred (ResourceAlreadyExistsException) when calling the CreateSchema operation: Another resource with Arn arn:aws:personalize:eu-west-1:979894173312:schema/retaildemostore-schema-users already exists.

**Comment by james-jory** [comment]
@patrick-239, is the Retail Demo Store project already deployed in the same account and region? If so, multiple deployments in the same account & region is current not supported. If that's not the case, did a previous delete the Retail Demo Store via CloudFormation fail to complete successfully in the same account & region? When you delete the Retail Demo Store stack, an attempt is made to remove all Personalize resources as well. However, if the delete process did not complete successfully, there may be remnants that need to be cleaned up manually.

If the Personalize dataset group is still present, this [script](https://gist.github.com/james-jory/62ddddf2f9180b77dd2a42e645b9d3b0) can be used to clean up all resources associated with the dataset group (including schemas). Otherwise, you will need to manually delete the schemas using the AWS cli or SDK.

**Comment by patrick-239** [comment]
Made several tests. The problem exist only in one region, so definitely not related to a source code.
