### ISSUE TITLE
Personalize SSM parameters don't work properly

### ISSUE THREAD

**Issue by blueblau1979** [aws-samples/retail-demo-store#241]
Quite similar issue with this thread #216.
I have set all the requirements step by step following the guide on Jupyter notebook. But there is no any recipe appearing on the retail store web UI, and recommendation service seemed don't take advantage of Personalize campaign...

Several screenshots as below:
![Screen Shot 2021-06-17 at 4 30 15 PM](https://user-images.githubusercontent.com/15047953/122361280-ae7f9c80-cf89-11eb-91dc-d6666488c14a.png)
<img width="912" alt="Screen Shot 2021-06-17 at 3 56 20 PM" src="https://user-images.githubusercontent.com/15047953/122361307-b5a6aa80-cf89-11eb-82cd-d28b781ed569.png">
<img width="896" alt="Screen Shot 2021-06-17 at 3 55 40 PM" src="https://user-images.githubusercontent.com/15047953/122361323-b93a3180-cf89-11eb-87eb-dd841ab5a979.png">

Regarding debug, I have tried to release recommendation CICD pipeline in CodePipeline, update CloudFormation template of retail store, restart recommendation task in ECS, etc. But those still not working...

For the logs of ECS recommendation service/task, I noticed that there was an error with "wsgi.errors" as blow:
<img width="927" alt="Screen Shot 2021-06-17 at 4 41 07 PM" src="https://user-images.githubusercontent.com/15047953/122362697-ec30f500-cf8a-11eb-8a73-038d20a55264.png">

Can anyone give me some clues to solve this issue? Thanks.

**Comment by james-jory** [comment]
@blueblau1979, I think I understand the issue. Everything is working correctly but we have a problem with the screenshots included with some of the documentation that indicate that the recipe ARN is displayed. The recipe ARN display logic was removed since it was redundant with the "Learn more about..." text next to the Personalize service logo/icon.

If you see the Personalize service logo/icon and the "Learn more about ..." above the display of products, then the recipe in the "Learn more about ..." text is what is in effect. For example, in the first screenshot where the section header says, "Inspired by your shopping trends" and the Personalize service logo/icon is displayed with "Learn more about user personalization powered by Amazon Personalize", the "user-personalization" recipe is being used to display those recommendations. If a personalize campaign is not in effect, the Personalize service icon is not displayed.

I apologize for the confusion and troubleshooting you had to do! We will get the screenshots updated to reflect the latest.
