### ISSUE TITLE
Issue with np.random.choice in Personalize Workshop

### ISSUE THREAD

**Issue by pscheri** [aws-samples/retail-demo-store#36]
Hi, I found a small error during the Create "User-Items Interactions Dataset" in 1.1-Personalize notebook.

During interaction simulation you define:

`category = np.random.choice(preferred_categories, 1, p=[0.6, 0.25, 0.15])[0] `

This generate an error because preferred_categories only have 2 items in the array and p= 3 slices fails.

**Comment by james-jory** [comment]
This issue was resolved by #34 which was merged yesterday. To get your deployment updated with the fixes, you have two choices.

1. Delete the RetailDemoStore CloudFormation stack from your account and re-deploy it.

- OR-

2. Update your existing deployment by following these steps.

If you used the CodeCommit deployment approach:
- Download the latest test user data file to your local machine. Download link: https://github.com/aws-samples/retail-demo-store/raw/master/src/users/src/users-service/data/users.json.gz
- In the AWS console for the account where you deployed the Retail Demo Store, browse to the CodeCommit `src` repo where the user data file is located (`/src/users/src/users-service/data`): https://console.aws.amazon.com/codesuite/codecommit/repositories/retaildemostore-src/browse/refs/heads/master/--/src/users/src/users-service/data
- Upload the new version of the `users.json.gz` file downloaded above.
- Commit your change by entering your name and email address. This will trigger a build and deploy cycle for the ECS services that should take ~5 minutes to complete. You can monitor progress in the CodePipeline console.
- While the ECS services are rebuilding, update the `1.1-Personalize.ipynb` notebook in SageMaker by downloading the [latest version of the notebook](https://github.com/aws-samples/retail-demo-store/blob/master/workshop/1-Personalization/1.1-Personalize.ipynb) and uploading it over the top of the existing notebook in Jupyter.

If you used the GitHub deployment approach:

- Update your fork of the Retail Demo Store repo in GitHub by fetching and merging the changes from the PR.
- Update the `1.1-Personalize.ipynb` notebook in SageMaker by downloading the [latest version of the notebook](https://github.com/aws-samples/retail-demo-store/blob/master/workshop/1-Personalization/1.1-Personalize.ipynb) and uploading it over the top of the existing notebook in Jupyter.
