### ISSUE TITLE
Unable to add items to cart or view cart

### ISSUE THREAD

**Issue by ewbolme** [aws-samples/retail-demo-store#432]
Currently I am unable to add items to the cart or view the cart this has implications on workshop 4.1 as well as it means I am unable to create a segment targeting users who have a shopping cart.

**Comment by gfaires** [comment]
Caused by the cart service failing to deploy - due to a go module loading error.  Redeploying the service through the build pipeline worked without hitting the same error.  Tested deploying the stack again, and didn't come across the issue, which suggests a transient issue.  Will reopen if it occurs more frequently
