### ISSUE TITLE
Issues with product recommendations in the demo app

### ISSUE THREAD

**Issue by ochsreekar** [aws-samples/retail-demo-store#48]
I had observed the following issues when using the demo app in our company.

Upon deploying the stack of retail demo store, evaluate the products listed in the Inspired by shopping trends section and there are issues in Viewing Product Recommendations:
•	When We log in as a predefined user in the demo application, Pre-defined users with each category, recommendations don’t match with the categories that were allotted. 
•	When we create new users and click on the new category with different items the recommendations were not changing on the home page.
Kindly let me know if there is a way to overcome these issues as well as if you could kindly check and fix the issues and make a new build available.

**Comment by james-jory** [comment]
When you deployed the product, did you select to have the Personalize campaigns automatically created for you? This was the "Yes/No" option in the CloudFormation template when you deployed. If you chose "Yes", a Lambda function would pull down some pre-made staged CSVs to train the Personalize models. Unfortunately, we had some inconsistencies between the staged CSVs and the users in the Users service (we regenerated the users but didn't recreate the CSVs to match the new users). Therefore, the users in the web UI did not match the users and interactions used to train the models resulting in unintuitive recommendations. 

To remedy this situation you can try two approaches:

1. Step through the [1.2-Personalize-Cleanup](https://github.com/aws-samples/retail-demo-store/blob/master/workshop/1-Personalization/1.2-Personalize-Cleanup.ipynb) workshop notebook to delete all of the Retail Demo Store Personalize resources and then step through the [1.1-Personalize](https://github.com/aws-samples/retail-demo-store/blob/master/workshop/1-Personalization/1.1-Personalize.ipynb) workshop to rebuild the Personalize models. Since the second workshop pulls users and items from the services to generate interactions, the models will match the current users in your deployment.
2. Delete the project entirely and redeploy. This can be done by deleting the Retail Demo Store CloudFormation stack and redeploying. Since we sync'd the CSVs in the staging bucket with the users database, the models will be in sync too.

Let us know if this works for you. I'll keep the issue open until we hear back. Apologies for the inconvenience.

**Comment by ochsreekar** [comment]
We will try it and revert back to you

**Comment by james-jory** [comment]
Realized I missed answering your second question:

> • When we create new users and click on the new category with different items the recommendations were not changing on the home page.

Clicking on categories do not generate training events since a category does not represent a specific product. Try clicking on product details for a few products in a category or two and then revisit the home view to see if recommendations change. It may take clicking on a few products before the service learns enough about cold/new users. 

You can find more details on what events are triggered and sent to Personalize [here](https://github.com/aws-samples/retail-demo-store/blob/master/documentation/2-Personalization.md#event-tracking).

**Comment by ochsreekar** [comment]
Thanks for the help! We tried it by deleting the cloud formation stack and redeploying the entire project. I have used the steps through the 1.1-Personalize workshop to rebuild the Personalize models. Now, we can get exact recommendations for pre-defined users and new users as well. 

Now, I am facing a new issue. When I create a new user and experimenting by clicking on multiple items in different categories the recommendations are changing on the home page but after some time (i.e. after 30 minutes) if I am trying again the recommendations are not popping on the home screen. Is there any session time limit for a user for recommendations using amazon personalize? Could you please help me on the same.

**Comment by james-jory** [comment]
> Now, I am facing a new issue. When I create a new user and experimenting by clicking on multiple items in different categories the recommendations are changing on the home page but after some time (i.e. after 30 minutes) if I am trying again the recommendations are not popping on the home screen. 

Can you provide more details on what's happening? Are recommendations not displaying at all (i.e. spinning "loading" icon never resolves to recommendations)? Or are the recommendations for the new user reverting back to popular items?

> Is there any session time limit for a user for recommendations using amazon personalize? Could you please help me on the same.

Although there is a time-based limit on the age of interactions that Personalize will consider when training models, we are no where near that limit here. Specifically, Personalize currently will train based on the most recent 500 million interactions and ignore older interactions. When you went through the 1.1-Personalize workshop, 500,000 interactions were generated so we're well below the service limit. Besides, we're talking about very recent interactions for a new user in this case so the 500M limit is not in play.

Also, for new/cold user interactions where retraining has not taken place, those interactions are managed by the event tracker and taken into account by the campaign to make personalization recommendations. Those should not time out either. 

Besides Personalize, there are web browser session timeouts in the web app to consider but 30 minutes is so short that shouldn't be the issue. The Retail Demo Store uses local storage for your user profile and Amazon Cognito for authentication. The Cognito token expiry is 30 days, I believe. Nevertheless, make sure you are still signed as your test user and not signed out (i.e. an anonymous user).

**Comment by james-jory** [comment]
@ochsreekar, are you still experiencing issues? If not, I will close this issue.

**Comment by sreekarippili** [comment]
Thanks for the help! I am not facing any issues and able to get recommendations for new users as well.

**Comment by james-jory** [comment]
Closing this issue since recommendations are working as expected.
