### ISSUE TITLE
The Deep links to the CloudFormation Launch templates are not working

### ISSUE THREAD

**Issue by neildcruz** [aws-samples/retail-demo-store#551]
The Deep links to the CloudFormation Launch templates are not working due to permission issues with the underlying S3 buckets hosting the template files.

I'm getting a 403 Access denied.

**Comment by alannoun** [comment]
Were you able to fix this issue? I'm dealing with the same error when I try to launch the CloudFormation templates.

**Comment by BastLeblanc** [comment]
Hi, thanks for raising the issue.
Can you confirm you're following these instructions https://github.com/aws-samples/retail-demo-store/blob/master/Developer-Instructions.md ?
There has been changes in the latest few weeks on deployment instructions

**Comment by david-cloudtech** [comment]
@BastLeblanc I am having the same issue with the S3 permissions, can you confirm that the Developer-Instructions is the only currently supported deployment option?

**Comment by BastLeblanc** [comment]
Yes that's the only current supported deployment option, and there's no current plans to use the public buckets.

Please let us know if that is an issue for you and we could help.

**Comment by david-cloudtech** [comment]
@BastLeblanc thanks for confirming! 

I am trying to deploy via the developer instructions right now. I'm facing an issue with the ApiGateway nested stack, the GetDiscounts resource fails to create with error:
`Resource handler returned message: "Cannot invoke "String.matches(String)" because "errorMsg" is null" (RequestToken: 1d5511c5-5d41-9ec5-ce8b-a4e88b056ea9, HandlerErrorCode: GeneralServiceException)`

Are you aware of what I can do to fix this?

**Comment by david-cloudtech** [comment]
Update: I was able to successfully deploy the stack after changing some default options. I had to fork the repo, include my Github token, and make sure SourceDeploymentType was set to GitHub (default value is CodeCommit). After these changes, the deployment succeeded.

**Comment by BastLeblanc** [comment]
Thanks @david-cloudtech for the update.

We have been searching for this specific issue without success, never seen it before. Based on your update I would assume it was a missing/misaligned parameter.
