### ISSUE TITLE
The following resource(s) failed to create: [PipelineGitHub].

### ISSUE THREAD

**Issue by shaders** [aws-samples/retail-demo-store#613]
Change deployment type from "CodeCommit" to "Github". Do not alter any other variables.

default:
repo name: retail-demo-store
branch: master
username: aws-samples
token: empty

Result:
Embedded stack arn:aws:cloudformation:us-east-1:408430694790:stack/retaildemostore-Services-4KVLQ9NX82H7-OffersService-1I220EQNBTDF7-Pipeline-A85FVASG0JEM/e5fbcbf0-557a-11ef-a0f8-0affd389bce1 was not successfully created: The following resource(s) failed to create: [PipelineGitHub]

How to investigate further?

**Comment by gfaires** [comment]
This is caused by not supplying a GitHubToken.  The documentation is incorrect, if Github is selected then a token is required.  This is an area we currently updating, for example, with an option to use the S3 bucket as the source rather than a source code repository.
If you have a GitHub account you can generate a personal access token easily by following these instructions: https://docs.github.com/en/authentication/keeping-your-account-and-data-secure/managing-your-personal-access-tokens#creating-a-fine-grained-personal-access-token
It just needs basic read-only rights to public repositories.
Once this is done, rather than entering this value directly into the template, I would recommend storing it in Secrets Manager and referencing it through a dynamic reference.  See https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/dynamic-references.html#dynamic-references-secretsmanager
We will update the documentation as part of the changes we are making in this area.
